# This file was generated by GoReleaser. DO NOT EDIT.
cask "kdbx" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3911139e11fe8bfeb71d822c7babb6240d93cd204f47ea2381695c3e7eb75359"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b6198920f2bfc1c0becc6fc6a0a93e0ddedbadb94a82452a3c15d58a5add727"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62fa295d4f58bcb0b05feeca44a5ba480c5b8f359a9ee31eb277b84843b6a207"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b31c157261b19d04424e18ddf01d69e2a88c4e93f064e7fe34eeab8242f8989d"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kdbx"
  desc "Per-project, per-env KeePassXC credentials for humans and agents"
  homepage "https://github.com/yarrasys/kdbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kdbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kdbx"]
    end
  end

  # No zap stanza required

end
