# This file was generated by GoReleaser. DO NOT EDIT.
cask "kdbx" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "53ee63bdd9384d5b0e5c524a436d9a55f8bb75e8d1e56606b877364d2ec16f91"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ff6a0c7ff30ec68a263822c2ea29d47c9b5883b21097d28e39c4266f295084d"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "652bc2c1f74f8cda5608c4489ab0daa6244d4dae00973a8af3590208dfe2ca6d"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0d7a79cdfa40ddf4da4e6d32d39794542a19e5dcfd485c18f3b24a4ba03454a"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kdbx"
  desc "Per-project, per-env KeePassXC credentials for humans and agents"
  homepage "https://github.com/yarrasys/kdbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kdbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kdbx"]
    end
  end

  # No zap stanza required

end
