# This file was generated by GoReleaser. DO NOT EDIT.
cask "kdbx" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "8956a025f310e765bebfc7769489b9e50cf02a9c7f4573f2faa86b63df42dca0"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfea2f9fa46cb1db6962eee5726a44736e900c64341e2b8f4bb7597b84366046"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ef66be839b32345f1e6396b68c69ea4ef2ff1d5a0f72ba427e3e43ab3240470"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "483b7e518e27252bd6f8ed28fc2c7c235c25e66133336edd165866e3f0cef418"
      url "https://github.com/yarrasys/kdbx/releases/download/v#{version}/kdbx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kdbx"
  desc "Per-project, per-env KeePassXC credentials for humans and agents"
  homepage "https://github.com/yarrasys/kdbx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kdbx"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kdbx"]
    end
  end

  # No zap stanza required

end
